### PR TITLE
 Keep track of ignored errors, resolves #2533 

### LINKED ISSUE #2533: Keep track of ignored errors
Users are often reluctant to report the first error they run into and chose to ignore it. If something does not work, they report it later and the error gets buried in the log. We should keep track of these and include them in the bug reports.

If any errors have been ignored, the PASS reporting option should be disabled. Even if everything worked, the correct status to report in this case is WONKY, as a workaround was required.

See also #2532.

### PR DESCRIPTION
**Pull request by NeoTheThird**
Users are often reluctant to report the first error they run into and chose to ignore it. If something does not work, they report it later and the error gets buried in the log. We should keep track of these and include them in the bug reports.

If any errors have been ignored, the PASS reporting option should be disabled. Even if everything worked, the correct status to report in this case is WONKY, as a workaround was required.

### CODE REVIEW

File: src/lib/errors.js [hunk 1]
```diff
@@ -43,13 +48,23 @@ class ErrorHandler {
    * @param {Function} restart callback
    * @param {Function} ignore callback
    */
-  toUser(error, errorLocation, restart, ignore) {
-    const errorString = `Error: ${errorLocation || "Unknown"}: ${error}`;
-    log.error(
-      errorString + (error.stack ? "\nstack trace: " + error.stack : "")
-    );
+  async toUser(error, errorLocation, restart, ignore) {
     if (window.getMain()) {
```
Comment (maciek134) [inline src/lib/errors.js:52]: Same here, reverse + return after `errorHandler.die` and the code gets a bit cleaner imo

**Review by maciek134 — DISMISSED** [review]
Turns out I only have two pretty opinionated comments, LGTM otherwise so feel free to ignore :)

File: src/lib/errors.js (hunk 1 above)
Comment (NeoTheThird) [inline src/lib/errors.js:52]:
```suggestion
    if (!window.getMain())
```

File: src/lib/errors.js [hunk 2]
```diff
@@ -43,13 +48,23 @@ class ErrorHandler {
...
+        mainEvent.emit(
+          "user:error",
+          message,
+          () => cont(restart),
+          () => cont(ignore)
+        );
+      });
     } else {
       errorHandler.die(error);
     }
```
Comment (NeoTheThird) [inline src/lib/errors.js:70]:
```suggestion
    return new Promise(resolve => {
      const message = `Error: ${errorLocation || "Unknown"}: ${error}`;
      const stack = error.stack ? "\nstack trace: " + error.stack : "";
      log.error(message + stack);
      const cont = continuePromise => {
        this.errors.push(message + stack);
        resolve(continuePromise ? continuePromise() : null);
      };
      mainEvent.emit(
        "user:error",
        message,
        () => cont(restart),
        () => cont(ignore)
      );
    });
```

File: src/lib/__mocks__/mainEvent.js [hunk 3]
```diff
@@ -4,8 +4,12 @@ const mainEvent = {
   on(event, handler) {
     handlers.set(event, handler);
   },
-  emit(event) {
-    handlers.get(event)();
+  emit(event, ...args) {
+    if (typeof handlers.get(event) == "function") {
```
[the remark this answers is not in the document]
Comment (NeoTheThird) [reply src/lib/__mocks__/mainEvent.js]: good point, thanks
